### ISSUE TITLE
执行configure 报错

### ISSUE THREAD

**Issue by wbstf** [zrlio/disni#45]
[root@localhost libdisni]# ./configure --with-jdk=/usr/java/jdk1.8.0_191-amd64
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking dependency style of gcc... (cached) gcc3
checking how to run the C preprocessor... gcc -E
checking for ibv_get_device_list in -libverbs... no
configure: error: disni requires libibverbs

**Comment by yuvaldeg** [comment]
It seems like your machine is missing libibverbs - you will need to install InfiniBand support on your machines in order to build disni.
Here's a tutorial explaining how to do so for Mellanox cards (and also general library deployments): https://community.mellanox.com/s/article/howto-setup-rdma-connection-using-inbox-driver--rhel--ubuntu-x

**Comment by wbstf** [comment]
> It seems like your machine is missing libibverbs - you will need to install InfiniBand support on your machines in order to build disni.
> Here's a tutorial explaining how to do so for Mellanox cards (and also general library deployments): https://community.mellanox.com/s/article/howto-setup-rdma-connection-using-inbox-driver--rhel--ubuntu-x

谢谢，

> It seems like your machine is missing libibverbs - you will need to install InfiniBand support on your machines in order to build disni.
> Here's a tutorial explaining how to do so for Mellanox cards (and also general library deployments): https://community.mellanox.com/s/article/howto-setup-rdma-connection-using-inbox-driver--rhel--ubuntu-x

谢谢~~libibverbs已经安装过了； disni还需要硬件支持吗

**Comment by PepperJo** [comment]
> disni还需要硬件支持吗
Yes, RDMA generally needs hardware support however you can run software RDMA devices like SoftRoCE or SoftiWARP.

**Comment by hanjian2086** [comment]
I get another error as following, can anyone help?


checking for netinet/in.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking rdma/rdma_cma.h usability... no
checking rdma/rdma_cma.h presence... no
checking for rdma/rdma_cma.h... no
configure: error: required header file missing

**Comment by PepperJo** [comment]
You need to install librdmacm.

**Comment by hanjian2086** [comment]
Thanks for your reply,the librdmacm already installed, error aways exists.

______________________________________________
sudo yum install librdmacm
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
Package librdmacm-13-7.el7.x86_64 already installed and latest version
Nothing to do

**Comment by patrickstuedi** [comment]
make sure you have the "-dev" package also installed for librdmacm and
libibverbs

**Comment by PepperJo** [comment]
The librdmacm package only contains the library (binary) but not the headers for development. So as @patrickstuedi pointed out you need to install the package with the headers. Depending on which distro you are using it might also be called "librdmacm-devel"

**Comment by wbstf** [comment]
Miss kernel-header file.    yum install




| |
汪兵
邮箱：wb18755132178@163.com
|

签名由 网易邮箱大师 定制

在2019年04月18日 17:40，Jonas Pfefferle 写道：

The librdmacm package only contains the library (binary) but not the headers for development. So as @patrickstuedi pointed out you need to install the package with the headers. Depending on which distro you are using it might also be called "librdmacm-devel"

**Comment by PepperJo** [comment]
@wbstf these are not kernel-header files. Everything is user-space here.

**Comment by hanjian2086** [comment]
@PepperJo  Yes,  Re-installed as librdmacm-devel ,libibverbs-devel Everything goes well.

**Comment by PepperJo** [comment]
Great. Closing this issue.
