### ISSUE TITLE
our target subsystem name does not follow the NVMe spec, but we already fixed with this, how can I change jNVMf code to connect our target well?

### ISSUE THREAD

**Issue by gwnet** [zrlio/disni#50]
Hello buddy from jNVMf

below is our target configure, I know it is not follow the NVMeOF spec nqn name. but we need use jNVMf to connect our target. could you please point to me how to change the code. or you can help me do that?

o- ports ................................................................................................................... [...]
  | o- 98 .................................................................................................................... [...]
  | | o- referrals ........................................................................................................... [...]
  | | o- subsystems .......................................................................................................... [...]
  | |   o- 16746e7c-32b4-47a1-b5ce-3428dea3ba22 .............................................................................. [...]
  | o- 99 .................................................................................................................... [...]
  | | o- referrals ........................................................................................................... [...]
  | | o- subsystems .......................................................................................................... [...]
  | |   o- 3dd75b04-ff89-424e-b604-3767ce066dba .............................................................................. [...]
  | o- 100 ................................................................................................................... [...]
  | | o- referrals ........................................................................................................... [...]
  | | o- subsystems .......................................................................................................... [...]
  | |   o- 4011675b-d20c-463f-a92b-0c15dc5c43cb .............................................................................. [...]
  | o- 101 ................................................................................................................... [...]
  | | o- referrals ........................................................................................................... [...]
  | | o- subsystems .......................................................................................................... [...]
  | |   o- 7a25f7a6-7a3d-47d7-9605-e55ab5f1c295 .............................................................................. [...]
  | o- 102 ................................................................................................................... [...]
  | | o- referrals ........................................................................................................... [...]
  | | o- subsystems .......................................................................................................... [...]
  | |   o- 8280409b-0742-485a-839f-4b3de2f99c60 .............................................................................. [...]
  | o- 103 ................................................................................................................... [...]
  | | o- referrals ........................................................................................................... [...]
  | | o- subsystems .......................................................................................................... [...]
  | |   o- 838eef5d-a6b3-4f30-b2de-b060c894eef7 .............................................................................. [...]
  | o- 104 ................................................................................................................... [...]
  | | o- referrals ........................................................................................................... [...]
  | | o- subsystems .......................................................................................................... [...]
  | |   o- 8615c539-a49a-40c7-b6fe-4772d2b511b8 .............................................................................. [...]
  | o- 105 ................................................................................................................... [...]
  | | o- referrals ........................................................................................................... [...]
  | | o- subsystems .......................................................................................................... [...]
  | |   o- 8753506b-c705-4daa-94c0-a9a456961db7 .............................................................................. [...]
  | o- 107 ................................................................................................................... [...]
  | | o- referrals ........................................................................................................... [...]
  | | o- subsystems .......................................................................................................... [...]
  | |   o- ae0ced01-f442-428d-a5cb-9e03359a2652 .............................................................................. [...]
  | o- 108 ................................................................................................................... [...]
  | | o- referrals ........................................................................................................... [...]
  | | o- subsystems .......................................................................................................... [...]
  | |   o- c87dc647-a7e7-4b6a-854d-331cae7d51c1 .............................................................................. [...]
  | o- 109 ................................................................................................................... [...]
  |   o- referrals ........................................................................................................... [...]
  |   o- subsystems .......................................................................................................... [...]
  |     o- e36b9b1a-e2ec-4120-92f6-18f50e3b554e .............................................................................. [...]
  o- subsystems .............................................................................................................. [...]
    o- 16746e7c-32b4-47a1-b5ce-3428dea3ba22 .................................................................................. [...]
    | o- allowed_hosts ....................................................................................................... [...]
    | o- namespaces .......................................................................................................... [...]
    |   o- 98 ................................................................................................................ [...]
    o- 3dd75b04-ff89-424e-b604-3767ce066dba .................................................................................. [...]
    | o- allowed_hosts ....................................................................................................... [...]
    | o- namespaces .......................................................................................................... [...]
    |   o- 99 ................................................................................................................ [...]
    o- 4011675b-d20c-463f-a92b-0c15dc5c43cb .................................................................................. [...]
    | o- allowed_hosts ....................................................................................................... [...]
    | o- namespaces .......................................................................................................... [...]
    |   o- 100 ............................................................................................................... [...]
    o- 7a25f7a6-7a3d-47d7-9605-e55ab5f1c295 .................................................................................. [...]
    | o- allowed_hosts ....................................................................................................... [...]
    | o- namespaces .......................................................................................................... [...]
    |   o- 101 ............................................................................................................... [...]
    o- 8280409b-0742-485a-839f-4b3de2f99c60 .................................................................................. [...]
    | o- allowed_hosts ....................................................................................................... [...]
    | o- namespaces .......................................................................................................... [...]
    |   o- 102 ............................................................................................................... [...]
    o- 838eef5d-a6b3-4f30-b2de-b060c894eef7 .................................................................................. [...]
    | o- allowed_hosts ....................................................................................................... [...]
    | o- namespaces .......................................................................................................... [...]
    |   o- 103 ............................................................................................................... [...]
    o- 8615c539-a49a-40c7-b6fe-4772d2b511b8 .................................................................................. [...]
    | o- allowed_hosts ....................................................................................................... [...]
    | o- namespaces .......................................................................................................... [...]
    |   o- 104 ............................................................................................................... [...]
    o- 8753506b-c705-4daa-94c0-a9a456961db7 .................................................................................. [...]
    | o- allowed_hosts ....................................................................................................... [...]
    | o- namespaces .......................................................................................................... [...]
    |   o- 105 ............................................................................................................... [...]
    o- ae0ced01-f442-428d-a5cb-9e03359a2652 .................................................................................. [...]
    | o- allowed_hosts ....................................................................................................... [...]
    | o- namespaces .......................................................................................................... [...]
    |   o- 107 ............................................................................................................... [...]
    o- c87dc647-a7e7-4b6a-854d-331cae7d51c1 .................................................................................. [...]
    | o- allowed_hosts ....................................................................................................... [...]
    | o- namespaces .......................................................................................................... [...]
    |   o- 108 ............................................................................................................... [...]
    o- e36b9b1a-e2ec-4120-92f6-18f50e3b554e .................................................................................. [...]
      o- allowed_hosts ....................................................................................................... [...]
      o- namespaces .......................................................................................................... [...]
        o- 109 ............................................................................................................... [...]
/>

**Comment by PepperJo** [comment]
This is a jNVMf related "issue" please open an issue there.
